paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/
  data_path: ../data/
  plotting_path: ./experiments/Keep_5\plots

experiment:
  name: Basic Experiment
  parameters:
    training_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        transformation: linear_univariate  # linear_univariate, random, or custom
        m: 4
        rho: None
        b: 0
    gold_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        transformation: linear_univariate  # linear_univariate, linear_mulivariate, random, or custom
        m: 4
        rho: None
        b: 0
    unlabelled_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        include: True  # Include a true y value if we want oracle, useles right now
        transformation: linear_univariate  # linear_univariate, random, or custom
        m: 4
        rho: None
        b: 0
    true_value: 8  # Compute this yourself, if not available, set to None
    n_its: 10000
    test_size: 0.2
    use_active_inference: False
    confidence_level: 0.95
  ind_var:
    name: noise  # this is really confusing right now because of rho/noise, will think of solution later
    vals:
      - 0.1
      - 0.25
      - 0.5
      - 0.9
    paths:
      - experiment.parameters.training_population.y_population.rho
      - experiment.parameters.gold_population.y_population.rho
      - experiment.parameters.unlabelled_population.y_population.rho
    plot_description: Noise between x and y
    label_description: Level of noise
  model:
    name: linear_regression
    # parameters: Will add later
  estimate: mean
  methods:
    - type: ppi
    - type: naive
    - type: classical
    - type: ppi_pp
      lambda: None  # Set None here for estimated optimal lambda
    #- type: stratified_ppi
  metrics:  # Make sure these are plural
    - widths
    - coverages 
  
plotting:
  plots:
      - type: violin
        y_metric: ci_width
        y_techniques:
          - technique: ppi
            label: PPI Widths
          - technique: classical
            label: Classic Widths
        title: Widths vs rho (noise)
        x_label: Method
        y_label: Widths
        file_name: widthsviolin.png
        show: False
      - type: line
        x: noise
        y_metric: ci_width
        y_techniques:
          - technique: ppi
            label: PPI Widths
          - technique: classical
            label: Classic Widths
        title: Widths vs rho (noise)
        x_label: Rho values
        y_label: Widths
        file_name: widthsplot.png
        show: False
      

reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log