paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/
  data_path: ../data/


experiment:
  name: Basic Experiment
  parameters:
    training_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 1
        beta: 1
        size: 10000
      y_population:
        transformation: linear_univariate  # linear_univariate, random, or custom
        m: 2
        rho: None
        b: 0
    gold_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 1
        beta: 1
        size: 10000
      y_population:
        transformation: linear_univariate  # linear_univariate, linear_mulivariate, random, or custom
        m: 2
        rho: None
        b: 0
    unlabelled_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 1
        beta: 1
        size: 10000
      y_population:
        include: True  # Include a true y value if we want oracle, useles right now
        transformation: linear_univariate  # linear_univariate, random, or custom
        m: 2
        rho: None
        b: 0
    true_value: 2  # Compute this yourself, if not available, set to None
    n_its: 1
    test_size: 0.2
    ppi_lambda: 0
    use_active_inference: False
  ind_var:
    name: rho
    vals:
      - 0.1
      - 0.25
      - 0.5
      - 0.9
    paths:
      - experiment.parameters.training_population.y_population.rho
      - experiment.parameters.gold_population.y_population.rho
      - experiment.parameters.unlabelled_population.y_population.rho
    plot_description: Noise between x and y
    label_description: Level of noise
  model:
    name: linear_regression
    # parameters: Will add later
  estimate: mean

      
  metrics:  # Make sure these are plural
    primary:  # metrics to be graphed
      - widths
    secondary:  # metrics to be stored but not graphed
      - coverages  
  


reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log