paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/


experiment:
  name: experiment
  description: This is a test file

reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log