paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/
  data_path: ../data/

experiment:
  name: exp2_test
  description: Label shift
  parameters:
    training_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        transformation: linear_gamma  # linear_univariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    gold_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 128
      y_population:
        transformation: linear_gamma  # linear_univariate, linear_mulivariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    unlabelled_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        include: True  # Include a true y value if we want oracle, useles right now
        transformation: linear_gamma  # linear_univariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    true_value: 16  # Compute this yourself, if not available, set to None
    n_its: 200
    test_size: 0.2
    use_active_inference: False
    confidence_level: 0.95
    cut_interval: True  # If True, will cut negative, upper lower intervals to 0
  ind_var:
    name: 
      - alpha
      - beta
    vals:
      - alpha: 2
        beta: 3
      - alpha: 3
        beta: 2
      - alpha: 2
        beta: 4
      - alpha: 4
        beta: 2
      - alpha: 2
        beta: 2
      - alpha: 3
        beta: 3
      - alpha: 4
        beta: 4
    paths:
      alpha:
        - experiment.parameters.gold_population.x_population.alpha
        - experiment.parameters.unlabelled_population.x_population.alpha
        - experiment.parameters.gold_population.y_population.alpha
        - experiment.parameters.unlabelled_population.y_population.alpha
      beta:
        - experiment.parameters.gold_population.x_population.beta
        - experiment.parameters.unlabelled_population.x_population.beta
        - experiment.parameters.gold_population.y_population.beta
        - experiment.parameters.unlabelled_population.y_population.beta
  model:
    name: linear_regression
    optuna: True
    # parameters: Will add later
  model_bias: True  # If false, will not calculate.
  estimate: mean
  methods:
    - type: ppi
    - type: naive
    - type: classical
    - type: ppi_pp
      lhat: null  # Set None here for estimated optimal lambda
    - type: ratio
      t_dist: True
    #- type: stratified_ppi
  metrics:  # Make sure these are plural
    - widths
    - coverages
  distances:
    - wasserstein
    - tv
  plot_distributions: True
  clipping: False
  varying_true_value: True  # Indicates if the true value varies between independent variables

plotting:
  plots:
    - type: line
      x: wasserstein
      y_metric: ci_width
      y_techniques:
        - technique: ppi
          label: PPI Widths
        - technique: classical
          label: Classic Widths
        - technique: naive
          label: Naive Widths
        - technique: ppi_pp
          label: PPI PP Widths
      title: Widths vs Wasserstein Distance
      x_label: Wasserstein Distance
      y_label: Widths
      file_name: widthsplotwasserstein.png
      show: False 
    - type: line
      x: tv
      y_metric: ci_width
      y_techniques:
        - technique: ppi
          label: PPI Widths
        - technique: classical
          label: Classic Widths
        - technique: naive
          label: Naive Widths
        - technique: ppi_pp
          label: PPI PP Widths
      title: Widths vs Wasserstein Distance
      x_label: Wasserstein Distance
      y_label: Widths
      file_name: widthsplottv.png
      show: False 
    - type: coverage
      x: wasserstein
      y_techniques:
        - technique: ppi
          label: PPI Coverage
        - technique: classical
          label: Classic Coverage
        - technique: naive
          label: Naive Coverage
        - technique: ppi_pp
          label: PPI PP Coverage
      title: Coverage vs rho (noise)
      x_label: Noise
      file_name: wassersteincoverage.png
      show: False
    - type: sample
      x: wasserstein
      y_metric: coverage
      y_techniques:
        - technique: ppi
          label: PPI Widths
        - technique: classical
          label: Classic Widths
        - technique: naive
          label: Naive Widths
        - technique: ppi_pp
          label: PPI PP Widths
      title: Coverage vs rho (noise)
      file_name: sampleplot.png
      show: False

reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log