paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/
  data_path: ../data/

experiment:
  name: exp2_test
  description: Label shift
  parameters:
    training_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        transformation: linear_gamma  # linear_univariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    gold_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 8
      y_population:
        transformation: linear_gamma  # linear_univariate, linear_mulivariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    unlabelled_population:
      x_population: 
        distribution: gamma_univariate
        alpha: 2
        beta: 2
        size: 10000
      y_population:
        include: True  # Include a true y value if we want oracle, useles right now
        transformation: linear_gamma  # linear_univariate, random, or custom
        m: 4
        rho: .85
        b: 0
        alpha: 2
        beta: 2
    true_value: 16  # Compute this yourself, if not available, set to None
    n_its: 2000
    test_size: 0.2
    use_active_inference: False
    confidence_level: 0.95
    cut_interval: True  # If True, will cut negative, upper lower intervals to 0
  ind_var:
    name: 
      - alpha
      - beta
    vals:
      - alpha: 4
        beta: 4
      - alpha: 5
        beta: 6
    paths:
      alpha:
        - experiment.parameters.gold_population.x_population.alpha
        - experiment.parameters.unlabelled_population.x_population.alpha
        - experiment.parameters.gold_population.y_population.alpha
        - experiment.parameters.unlabelled_population.y_population.alpha
      beta:
        - experiment.parameters.gold_population.x_population.beta
        - experiment.parameters.unlabelled_population.x_population.beta
        - experiment.parameters.gold_population.y_population.beta
        - experiment.parameters.unlabelled_population.y_population.beta
  model:
    name: linear_regression
    optuna: True
    # parameters: Will add later
  model_bias: True  # If false, will not calculate.
  estimate: mean
  methods:
    - type: ppi
    - type: naive
    - type: classical
    - type: ppi_pp
      lhat: null  # Set None here for estimated optimal lambda
    - type: ratio
      t_dist: True
    #- type: stratified_ppi
  metrics:  # Make sure these are plural
    - widths
    - coverages
  distances:
    - wasserstein
    - tv

      

reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log