paths:
  src_path: ./src/
  configs_path: ../configs/
  experiments_path: ../experiments/
  data_path: ../data/

experiment:
  name: 100kt_nc_nonlin_xgb
  description: Label shift, 100k training, no clipping, non-linear data, xgboost
  parameters:
    training_population:
      x_population: 
        distribution: normal_univariate
        mean: 0
        std: 4
        size: 100000
      y_population:
        transformation: experimental_six  # linear_univariate, random, or custom
    gold_population:
      x_population: 
        distribution: normal_univariate
        mean: 0
        std: 4
        size: 128
      y_population:
        transformation: experimental_six  # linear_univariate, linear_mulivariate, random, or custom
    unlabelled_population:
      x_population: 
        distribution: normal_univariate
        mean: 0
        std: 4
        size: 10000
      y_population:
        include: True  # Include a true y value if we want oracle, useles right now
        transformation: experimental_six
    true_value: 16  # Compute this yourself, if not available, set to None
    n_its: 1000
    test_size: 0.2
    use_active_inference: False
    confidence_level: 0.95
    cut_interval: True  # If True, will cut negative, upper lower intervals to 0
  ind_var:
    name: 
      - mean
      - std
    vals:
      - mean: 0
        std: 4
      - mean: 2
        std: 4
      - mean: -2
        std: 4
      - mean: 4
        std: 4
      - mean: -4
        std: 4
      - mean: 0
        std: 5
      - mean: 0
        std: 6
    paths:
      mean:
        - experiment.parameters.gold_population.x_population.mean
        - experiment.parameters.unlabelled_population.x_population.mean
        - experiment.parameters.gold_population.y_population.mean
        - experiment.parameters.unlabelled_population.y_population.mean
      std:
        - experiment.parameters.gold_population.x_population.std
        - experiment.parameters.unlabelled_population.x_population.std
        - experiment.parameters.gold_population.y_population.std
        - experiment.parameters.unlabelled_population.y_population.std
  model:
    name: xgboost
    optuna: True
    trials: 5
    # parameters: Will add later
  model_bias: True  # If false, will not calculate.
  estimate: mean
  methods:
    - type: ppi
    - type: naive
    - type: classical
    - type: ppi_pp
      lhat: null  # Set None here for estimated optimal lambda
    - type: ratio
      t_dist: True
    #- type: stratified_ppi
  metrics:  # Make sure these are plural
    - widths
    - coverages
  distances:
    - wasserstein
    - tv
  plot_distributions: True
  dist_family: normal
  clipping: False
  varying_true_value: True  # Indicates if the true value varies between independent variables
  remove_gold: False

plotting:
  plots:
    - type: line
      x: wasserstein
      y_metric: ci_width
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
      title: Widths vs Wasserstein Distance
      x_label: Wasserstein Distance
      y_label: Widths
      file_name: widthsplotwasserstein.png
      show: False 
    - type: line
      x: tv
      y_metric: ci_width
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
      title: Widths vs Total Variation Distance
      x_label: Total Variation
      y_label: Widths
      file_name: widthsplottv.png
      show: False 
    - type: coverage
      x: wasserstein
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
      title: Coverage vs Wasserstein Distance
      x_label: Wasserstein Distance
      file_name: wassersteincoverage.png
      show: False
    - type: sample
      x: wasserstein
      y_metric: coverage
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
      title: Coverage vs rho (noise)
      file_name: sampleplot.png
      show: False
    - file_name: widths_mean_shifts.png
      processing:
        - col: std
          type: isolate_values
          vals:
            - 4
      show: False
      title: Widths vs mean Value Shifts
      type: line
      x: mean
      x_label: Mean Values
      y_label: Widths
      y_metric: ci_width
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
    - file_name: widths_std_shifts.png
      processing:
        - col: mean
          type: isolate_values
          vals:
            - 0
      show: False
      title: Widths vs Std Value Shifts
      type: line
      x: std
      x_label: Std Values
      y_label: Widths
      y_metric: ci_width
      y_techniques:
        - label: PPI
          technique: ppi
        - label: Classic
          technique: classical
        - label: Naive
          technique: naive
        - label: PPI++
          technique: ppi_pp
    - type: line
      x: wasserstein
      y_metric: relative_improvement
      y_techniques:
        - technique: ppi
          label: PPI
        - technique: ppi_pp
          label: PPI++
      title: Relative Improvement vs Wasserstein Distance
      x_label: Wasserstein Distance
      y_label: Relative Improvement
      file_name: relative_improvement_wass.png
      show: False
    - type: line
      x: tv
      y_metric: relative_improvement
      y_techniques:
        - technique: ppi
          label: PPI
        - technique: ppi_pp
          label: PPI++
      title: Relative Improvement vs Total Variation
      x_label: Total Variation
      y_label: Relative Improvement
      file_name: relative_improvement_tv.png
      show: False
    - file_name: relative_mean_shifts.png
      processing:
        - col: std
          type: isolate_values
          vals:
            - 4
      show: false
      title: Relative Improvement vs Mean Value Shifts
      type: line
      x: mean
      x_label: Mean Values
      y_label: Relative Improvement
      y_metric: relative_improvement
      y_techniques:
        - label: PPI
          technique: ppi
        - label: PPI++
          technique: ppi_pp
    - file_name: relative_std_shifts.png
      processing:
        - col: mean
          type: isolate_values
          vals:
            - 0
      show: false
      title: Relative Improvement vs Std Value Shifts
      type: line
      x: std
      x_label: Std Values
      y_label: Relative Improvement
      y_metric: relative_improvement
      y_techniques:
        - label: PPI
          technique: ppi
        - label: PPI++
          technique: ppi_pp

reproducibility:
  seed: 42

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: ../logs/log.log